# Examen Programmation avancée 2022_2023 SRI2A

Durée 1h30, Documents et machines autorisées, barême indicatif

## Exercice 1
On a pour objectif de faire un dictionnaire de scrabble, à partir d’une liste de mots.  
Un dictionnaire de scrabble permet de trouver les mots faisables à partir d’un ensemble de lettres donné.  

On va donc essayer de rentrer l’information sous forme d’un dictionnaire python, où les clefs seront des chaines avec les lettres, classées alphabétiquement. par exemple “aacdef” est une clef, à laquelle est associée le seul mot “facade”. A la clef “cehin” sont associés les mots “chien”, “chine” et “niche”.  

Vous pourrez utiliser les fonctions suivantes sur les chaines:

* **`len(s)` donne la longueur d’une chaine.**
    * ex : `len(“chien”) -> 5`
* **`sorted(s)` renvoie une liste triée avec les lettres de la chaine s.**
    * ex : `sorted(“chien”) -> [“c”,“e”,“h”,“i”,“n”]`
* **`c.join(liste)` renvoie une chaine constitué des éléments de liste séparés par le caractère c.**
    * ex : `“-”.join([“a”,“b”,“c”]) -> “a-b-c”`

**Questions**  
*il n’est pas forcément besoin d’avoir écrit une fonction pour s’en servir ensuite*

1. **Ecrivez une fonction `mot2clef` qui associe une clef triée à une chaine**
* **Input** : `mot2clef(“chien”)`
* **Output** :`“cehin”`

In [2]:
def mot2clef(mot):
    return "".join(sorted(mot))

# Exemple d'utilisation
print(mot2clef("facade"))
print(mot2clef("chien"))

aacdef
cehin


2. **Ecrivez une fonction `faire_dico` qui prend une liste de mots en entrée et renvoie un dictionnaire de clef: pour chaque clef le résultat stocke la liste des mots qui correspondent à la clef.**
* **Input** : `input = ["chien","chine","banane","niche","tri","rit"]`  
* **Output** : `{"cehin":["chien","niche","chine"], "aabenn":["banane"], "irt":["tri","rit"]}`

In [3]:
def faire_dict(liste_mot):
    d = {}                          # Crée un dictionnaire vide
    for mot in liste_mot:           # Parcourt chaque mot dans la liste d'entrée
        clef = mot2clef(mot)        # Appelle la fonction mot2clef pour obtenir une clé à partir du mot
        if clef in d:               # Si la clé est déjà présente dans le dictionnaire
            d[clef].append(mot)     # Ajoute le mot à la liste associée à cette clé
        else:                       # Si la clé n'existe pas encore dans le dictionnaire
            d[clef] = [mot]         # Crée une nouvelle clé avec le mot en tant que première entrée d'une liste

    return d                        # Retourne le dictionnaire résultant

# Exemple d'utilisation
input = ["chien", "chine", "banane", "niche", "tri", "rit"]
print(faire_dict(input))            # Appelle la fonction avec la liste d'entrée et affiche le dictionnaire résultant

{'cehin': ['chien', 'chine', 'niche'], 'aabenn': ['banane'], 'irt': ['tri', 'rit']}


3. **Faire une fonction `par_taille` qui prend en entrée un dictionnaire similaire à ceux renvoyés par `faire_dico`, et renvoie un dictionnaire de dictionnaires indexés par la longueur de leurs clefs.**

Sur la sortie de l’exemple précédent on aurait donc comme résultat (attention à faire quelque chose de bien
général si on avait par exemple tous les mots du dictionnaire en entrée) :

`{5: {‘cehin’: [‘chien’, ‘chine’, ‘niche’]}, 6: {‘aabenn’: [‘banane’]}, 3: {‘irt’: [‘tri’, ‘rit’]}}`

In [4]:
def par_taille(d):
    r = {}                                  # Crée un dictionnaire vide pour le résultat
    for clef, mots in d.items():            # Parcourt chaque clé et liste de mots dans le dictionnaire d'entrée
        longueur_clef = len(clef)           # Calcule la longueur de la clé
        if longueur_clef in r:              # Si la longueur de clé existe déjà dans le dictionnaire résultant
            r[longueur_clef][clef] = mots   # Ajoute la clé et ses mots au dictionnaire existant
        else:                               # Si la longueur de clé n'existe pas encore dans le dictionnaire résultant
            r[longueur_clef] = {clef: mots} # Crée un nouveau dictionnaire avec la clé et ses mots

    return r                                # Retourne le dictionnaire résultant

# Exemple d'utilisation
d = {"cehin": ["chien", "chine", "niche"], "aabenn": ["banane"], "irt": ["tri", "rit"]}
print(par_taille(d))                        # Appelle la fonction avec le dictionnaire d'entrée et affiche le dictionnaire résultant

{5: {'cehin': ['chien', 'chine', 'niche']}, 6: {'aabenn': ['banane']}, 3: {'irt': ['tri', 'rit']}}


## Exercice 2 : objets
On va définir une classe MultiSet qui représente un type d’ensemble où un élément peut être présent
plusieurs fois.  
> ex : {( A, 2), ( B, 4), (C, 5)}  
(un multiset qui contient A 2 fois, B 4 fois, C 5 fois).

Vous pouvez choisir comment vous voulez stocker les informations dans la classe (attributs).  

**Ecrivez les méthodes suivantes**
* `__init__` pour créer un multiset vide
* `addElem` pour ajouter un élément, avec le nombre de fois où il est présent
* `add`, qui fait l’ajout de 2 multisets: chaque élément est présent la somme de fois qu’il est présent dans
les 2
* `intersection`: qui prend les éléments de 2 multisets, comptés avec le minimum des comptes dans les 2
multisets
* `union`: similaire à intersection, avec le max comme comptage.

In [20]:
class MultiSet:
    def __init__(self):
        # Crée un multiset vide sous forme d'un dictionnaire où les clés sont les éléments et les valeurs sont les nombres de fois qu'ils sont présents.
        self.elements = {}

    def addElem(self, element, count):
        # Ajoute un élément avec le nombre de fois spécifié au multiset.
        if element in self.elements:
            self.elements[element] += count
        else:
            self.elements[element] = count

    def add(self, other):
        # Fait l'ajout de deux multisets, chaque élément est présent la somme de fois qu'il est présent dans les deux.
        result = MultiSet()
        for element, count in self.elements.items():
            result.addElem(element, count)
        for element, count in other.elements.items():
            result.addElem(element, count)
        return result

    def intersection(self, other):
        # Prend les éléments de deux multisets, comptés avec le minimum des comptes dans les deux multisets.
        result = MultiSet()
        for element in self.elements:
            if element in other.elements:
                result.addElem(element, min(self.elements[element], other.elements[element]))
        return result

    def union(self, other):
        # Similaire à l'intersection, avec le maximum comme comptage.
        result = MultiSet()
        for element, count in self.elements.items():
            result.addElem(element, count)
        for element, count in other.elements.items():
            if element in result.elements:
                result.elements[element] = max(result.elements[element], count)
            else:
                result.addElem(element, count)
        return result

    def __str__(self):
        # Permet d'afficher le multiset sous forme de chaîne de caractères.
        return str(self.elements)

# Exemples d'utilisation
multiSet1 = MultiSet()
multiSet1.addElem('A', 2)
multiSet1.addElem('B', 4)
multiSet1.addElem('C', 5)

multiSet2 = MultiSet()
multiSet2.addElem('A', 3)
multiSet2.addElem('B', 2)
multiSet2.addElem('D', 1)

print("MultiSet 1:", multiSet1)
print("MultiSet 2:", multiSet2)

result_add = multiSet1.add(multiSet2)
print("Addition:", result_add)

result_intersection = multiSet1.intersection(multiSet2)
print("Intersection:", result_intersection)

result_union = multiSet1.union(multiSet2)
print("Union:", result_union)


MultiSet 1: {'A': 2, 'B': 4, 'C': 5}
MultiSet 2: {'A': 3, 'B': 2, 'D': 1}
Addition: {'A': 5, 'B': 6, 'C': 5, 'D': 1}
Intersection: {'A': 2, 'B': 2}
Union: {'A': 3, 'B': 4, 'C': 5, 'D': 1}


## Exercice 3: calcul vectoriel

### Introduction aux méthodes numpy

Indice: en plus des opérations de base numpy, il sera utile de faire appel aux méthodes suivantes :  
* `.reshape`: méthode sur un vecteur/matrice/. . . numpy qui change les dimensions si le nombre
d’éléments est compatible
* `.means`(axis=. . . ) qui fait la moyenne des éléments d’une matrice selon la dimension donnée par axis.  
Par exemple 0 pour les “lignes”, “1” pour les colonnes


### Détail de quelques fonctions de la bibliothèque NumPy

1. **`np.arange(start,stop,step,dtype=None)`** (pour "array range") 
   - **Crée un tableau NumPy contenant une séquence de nombres régulièrement espacés.**
   - `start` (optionnel) : La valeur de départ de la séquence. Par défaut, `start` est égal à 0.
   - `stop` : La valeur (exclusive) à laquelle la séquence s'arrête.
   - `step` (optionnel) : L'incrément entre les valeurs de la séquence. Par défaut, `step` est égal à 1.
   - `dtype` (optionnel) : Le type de données des éléments dans le tableau. Par défaut, NumPy détermine le type en fonction des valeurs fournies.

   ```python
   import numpy as np
   arr = np.arange(1, 10, 2)  # Crée un tableau avec des nombres de 1 à 9 (exclus), avec un pas de 2.
   ```

2. **`array.reshape(shape)`** :
   - **Change la forme d'un tableau NumPy sans modifier les données qu'il contient en prenant en compte les dimensions souhaitées pour le tableau.**
   - `shape` : Un tuple qui spécifie les nouvelles dimensions du tableau.

   ```python
   import numpy as np
   arr = np.arange(1, 10)  # Crée un tableau de 1D avec des nombres de 1 à 9.
   matrice = arr.reshape((3, 3))  # Remodèle le tableau en une matrice 3x3.
   ```

   Dans le code que vous avez fourni, la fonction `carre(N)` utilise `np.arange(1, N*N + 1)` pour générer un tableau 1D contenant des nombres de 1 à `N*N`. Ensuite, la méthode `reshape(N, N)` est utilisée pour remodeler ce tableau en une matrice carrée de taille `N` x `N`. Ainsi, vous obtenez une matrice carrée de taille `N` x `N` remplie de nombres de 1 à `N*N`.

3. **`numpy.mean(a, axis=None, dtype=None, out=None, keepdims=<no value>)`** :
   - **Calcule la moyenne en additionnant tous les éléments du tableau le long de l'axe spécifié** (ou de l'ensemble du tableau si aucun axe n'est spécifié) **et en divisant cette somme par le nombre total d'éléments**. 
   - `a`: Le tableau NumPy sur lequel vous souhaitez calculer la moyenne.
   - `axis` (optionnel) : L'axe le long duquel la moyenne doit être calculée. Par défaut, la moyenne est calculée sur l'ensemble du tableau, ce qui signifie que tous les éléments sont pris en compte pour le calcul de la moyenne. Si vous spécifiez un axe, la moyenne est calculée le long de cet axe, créant un tableau de moyennes le long de cet axe.
   - `dtype` (optionnel) : Le type de données que vous souhaitez pour le résultat. Par défaut, le type de données est déterminé automatiquement.
   - `out` (optionnel) : Un tableau de sortie où vous pouvez stocker le résultat. Cela peut être utile pour économiser de la mémoire si vous avez déjà un tableau alloué pour le résultat.
   - `keepdims` (optionnel) : Si vous définissez `keepdims=True`, les dimensions de l'axe sur lequel vous avez calculé la moyenne sont conservées dans le résultat. Cela signifie que le résultat est également un tableau, mais avec des dimensions conservées. Par défaut, `keepdims` est à `<no value>` (ce qui signifie que les dimensions ne sont pas conservées).

   ```python
   import numpy as np
   arr = np.array([1, 2, 3, 4, 5])
   moyenne = np.mean(arr)  # Calcule la moyenne de tous les éléments du tableau
   print(moyenne)  # Affiche la moyenne, qui est (1+2+3+4+5)/5 = 3.0
   ```

   Dans cet exemple, la méthode `.mean()` calcule la moyenne de l'ensemble des éléments du tableau `arr`, ce qui donne 3.0 comme résultat.
   

### Application
Pour ces exercices, vous ne devez faire aucun boucle.
L’usage d’une boucle entraine 0 à la question

1. **Définir une fonction qui crée une matrice numpy carrée NxN à partir d’un N donnée, avec les entiers de 1 à NxN Par exemple carre(5) renverrait**

```python
array([[ 1, 2, 3, 4, 5],
[ 6, 7, 8, 9, 10],
[11, 12, 13, 14, 15],
[16, 17, 18, 19, 20],
[21, 22, 23, 24, 25]])
```

In [21]:
import numpy as np                                  # Importe la bibliothèque NumPy sous le nom np

def carre(N):
    if N <= 0:                                      # Si N est inférieur ou égal à zéro
        return None                                 # Renvoyer None
    else:                                           # Sinon
        return np.arange(1, N*N + 1).reshape(N, N)  # Crée un tableau NumPy en utilisant arange() et reshape()

N = 5                                               # Définit la taille N de la matrice carrée
resultat = carre(N)                                 # Appelle la fonction carre(N) pour créer la matrice carrée
print(resultat)                                     # Affiche la matrice résultante

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


2. **Ecrire une fonction qui prend une matrice et renvoie le vecteur des moyennes des 2 dernières colonnes.**  
Par exemple pour la matrice exemple de la question 1 le résultat serait :
```array([14., 15.])```

In [22]:
import numpy as np

def moyennes_dernieres_colonnes(matrice):
    if matrice.shape[1] < 2:                        # Vérifie que la matrice a au moins 2 colonnes
        return None                                 # Impossible de calculer les moyennes
    dernieres_colonnes = matrice[:, -2:]            # Sélectionne les 2 dernières colonnes
    moyenne = np.mean(dernieres_colonnes, axis=0)   # Calcule la moyenne le long de l'axe des colonnes (axis=0)
    return moyenne                                  # Retourne la moyenne calculée

# Exemple d'utilisation
matrice_exemple = carre(5)                          # On utilise la fonction carre définie dans la question précédente
resultat = moyennes_dernieres_colonnes(matrice_exemple)
print(resultat)


[14. 15.]


3. **Ecrire une fonction qui calcule tous les termes de la suite Un ci-dessous depuis n=1 à n=K et les renvoie dans un vecteur numpy:**

u_n=(1+(1/n))^n

In [23]:
import numpy as np

def calcul_suite_U_n(K):
    n = np.arange(1, K + 1)     # Vecteur de 1 à K
    U_n = (1 + 1/n)**n
    return U_n

# Exemple d'utilisation
K = 10                          # Paramètre modifiable
resultat = calcul_suite_U_n(K)
print(resultat)

[2.         2.25       2.37037037 2.44140625 2.48832    2.52162637
 2.5464997  2.56578451 2.58117479 2.59374246]
