# Examen Python SRI 2023-2024

**Nom : GIBERT**  
**Prénom : Alexis**

**Durée 1h30, Documents et machines autorisées, barême indicatif**

Les parties sont indépendantes

A l'intérieur d'une partie, vous pouvez utiliser les fonctions définies précédemment, même si vous ne les avez pas codées (mais bien sur, ce sera plus dur à tester dans le notebook).

## Partie 1

On va considérer des étudiants qui ont des notes à des matières, et chaque matière a un coefficient dans la moyenne finale. 
Par exemple: (en listant les coeffs et les noms des matières dans le même ordre que les notes) 

In [3]:
all_etudiants = ['superdupont', 'asterix', 'tyrion']
coeffs = [5,2,2]
notes_par_matière = [[15, 2, 5], [8, 5, 20], [19, 15, 13]]
matières = ["poterie","anglais","c++"]

#### 1.1 

Ecrire une fonction  `notes_par_etud` qui prend en entrée les notes par matières et renvoie une liste des listes de notes par étudiant.  
Sur l'exemple on doit avoir: 
```python
notes_par_etud(notes_par_matière)
[[15, 8, 19], [2, 5, 15], [5, 20, 13]]
```

In [4]:
def notes_par_etud(notes_par_matiere):
    notes_par_etudiant = list(map(list, zip(*notes_par_matiere))) # J'ai préféré utiliser la méthode "zip" pour creer des tuples et ainsi transposer la matrice des notes par matière en matrice des notes par étudiant
    return notes_par_etudiant

print(notes_par_etud(notes_par_matière))

[[15, 8, 19], [2, 5, 15], [5, 20, 13]]


#### 1.2

Ecrire une fonction `make_dict` qui fait un dictionnaire des notes par étudiants avec leur nom, à partir de la liste d'étudiants et des notes par matière. 
Sur l'exemple, elle renverrait
```python
{'superdupont': [15, 8, 19], 'asterix': [2, 5, 15], 'tyrion': [5, 20, 13]}
```

In [5]:
def make_dict(etudiants, notes_par_matière):
    notes_par_etudiant = notes_par_etud(notes_par_matière)
    notes_dict = {}
    for i in range(len(etudiants)):
        notes_dict[etudiants[i]] = notes_par_etudiant[i]
    return notes_dict

print(make_dict(all_etudiants, notes_par_matière))

{'superdupont': [15, 8, 19], 'asterix': [2, 5, 15], 'tyrion': [5, 20, 13]}


#### 1.3 
* Ecrire une fonction `moyenne_1` qui fait la moyenne d'une liste de notes (pour 1 etudiant seulement) pondérée par une liste de coefficients
* Ecrire une fonction `moyenne` qui prend en entreé un dictionnaire comme la sortie de la fonction `make_dict `
et calcule un dictionnaire des moyennes par étudiant. 
* Ecrire une fonction `ajout_moyenne` qui prend en entrée aussi un dictionnaire de notes par étudiants et ajoute la moyenne comme dernière valeur. 

```python
# sur l'exemple: 
{'superdupont': [15, 8, 19, 14.333333333333334],
 'asterix': [2, 5, 15, 5.555555555555555],
 'tyrion': [5, 20, 13, 10.11111111111111]}
```

In [6]:
def moyenne_1(notes, coefficients):
    total = sum([note * coeff for note, coeff in zip(notes, coefficients)])
    total_coefficients = sum(coefficients)
    moyenne = total / total_coefficients if total_coefficients != 0 else 0
    return moyenne

def moyenne(notes_dict, coefficients):
    moyennes_dict = {}
    for nom, notes in notes_dict.items():
        moyenne_etudiant = moyenne_1(notes, coefficients)
        moyennes_dict[nom] = moyenne_etudiant
    return moyennes_dict

def ajout_moyenne(notes_dict, coefficients):
    moyennes_dict = moyenne(notes_dict, coefficients)
    for nom, moyenne_etudiant in moyennes_dict.items():
        notes_dict[nom].append(moyenne_etudiant)
    return notes_dict

notes_dict = make_dict(all_etudiants, notes_par_matière)
ajout_moyenne(notes_dict, coeffs)
print(notes_dict)

{'superdupont': [15, 8, 19, 14.333333333333334], 'asterix': [2, 5, 15, 5.555555555555555], 'tyrion': [5, 20, 13, 10.11111111111111]}


#### 1.4

Ecrire une fonction `valide` qui prend en entrée un dictionnaire de notes + moyennes comme au 1.3, et renvoie la liste des étudiants qui remplissent les conditions suivantes: 
  - au moins 6 à chaque matière
  - la moyenne supérieure ou égale à 10
  
Sur l'exemple, seul superdupont remplit les conditions

In [7]:
def valide(notes_dict):
    etudiants_valides = []
    for nom, notes in notes_dict.items():
        if all(note >= 6 for note in notes[:-1]) and notes[-1] >= 10:
            etudiants_valides.append(nom)
    return etudiants_valides

notes_dict = make_dict(all_etudiants, notes_par_matière)
ajout_moyenne(notes_dict, coeffs)
print(valide(notes_dict))

['superdupont']


#### 1.5 

Généraliser la fonction précédente en une fonction `passe_custom` pour qu'elle prenne en argument en plus une liste de fonctions, chacune des fonctions testant une condition différente sur la liste des notes d'un étudiant seul.  
Recalculer le résultat précédent avec cette fonction 

In [8]:
def passe_custom(notes_dict, condition_functions):
    etudiants_valides = []
    for nom, notes in notes_dict.items():
        if all(condition(notes) for condition in condition_functions):
            etudiants_valides.append(nom)
    return etudiants_valides

def condition_matiere_superieure_ou_egale_a_six(notes):
    return all(note >= 6 for note in notes[:-1])

def condition_moyenne_superieure_ou_egale_a_dix(notes):
    return notes[-1] >= 10

notes_dict = make_dict(all_etudiants, notes_par_matière)
ajout_moyenne(notes_dict, coeffs)
condition_functions = [condition_matiere_superieure_ou_egale_a_six, condition_moyenne_superieure_ou_egale_a_dix]
print(passe_custom(notes_dict, condition_functions))

['superdupont']


## Partie 2

#### 2.1
Définir une classe `Jury` qui est initialisé à partir d'une liste de noms d'étudiants, de noms de matières, et de coefficients par matière. 

#### 2.2
Définir les méthodes suivantes (ici vous pouvez utiliser les fonctions de la partie 1 à l'intérieur de ces méthodes: 
  - une méthode `add_notes` qui prend en paramètre une liste de notes par matière et va stocker dans l'objet un dictionnaire de notes similaires au résultat de la partie 1
  - une méthode `add_moyenne` qui va ajouter la moyenne dans la liste des notes de chaque étudiant
  - une méthode `qui_passe`, qui renvoie la liste des étudiants acceptés (comme partie 1)

In [9]:
j = Jury(all_etudiants,coeffs,matières)
j.add_notes(notes_par_matière)
print(j.note_dict)
j.add_moyenne()
print(j.qui_passe())
print(j.note_dict)

NameError: name 'Jury' is not defined

In [10]:
class Jury:
    def __init__(self, etudiants, coefficients, matières):
        self.etudiants = etudiants
        self.coefficients = coefficients
        self.matieres = matières
        self.note_dict = {}
    
    def add_notes(self, notes_par_matière):
        self.note_dict = make_dict(self.etudiants, notes_par_matière)
    
    def add_moyenne(self):
        for etudiant in self.note_dict:
            moy = moyenne_1(self.note_dict[etudiant], self.coefficients)
            self.note_dict[etudiant].append(moy)
    
    def qui_passe(self, condition_functions):
        return passe_custom(self.note_dict, condition_functions)

j = Jury(all_etudiants, coeffs, matières)
j.add_notes(notes_par_matière)
print(j.note_dict)
j.add_moyenne()
print(j.qui_passe(condition_functions))
print(j.note_dict)


{'superdupont': [15, 8, 19], 'asterix': [2, 5, 15], 'tyrion': [5, 20, 13]}
['superdupont']
{'superdupont': [15, 8, 19, 14.333333333333334], 'asterix': [2, 5, 15, 5.555555555555555], 'tyrion': [5, 20, 13, 10.11111111111111]}


## Partie 3
On va faire en partie la même chose que la partie 1 en partant de zéro avec numpy.  
**Attention: on ne peut pas réutiliser les fonctions des parties précédentes, et il ne doit y avoir aucune boucle, sinon les questions valent 0**  
Vous pouvez par contre utiliser des fonctions de la partie 3 pour faire des fonctions qui viennent après dans la partie. 

Rappel de quelques méthodes numpy, sur un vecteur a, dont certaines peuvent servir ici : 
 - `a.mean()` fait la moyenne de toutes les valeurs; `a.mean(axis=0)` fait la moyenne selon l'axe 0
 - idem pour `sum`, `min`, `max`
 - `a.T` est la transposée de a
 - `list(a)` transforme a en une liste selon la première dimension de a
 - `a.reshape(new_shape)`: permet de redéfinir une matrice avec de nouvelles dimensions (si le nb d'éléments correspond), eg un vecteur de 20 valeurs peut etre "reshaped" en une matrice de 5x4 valeurs
 - `np.concatenate(liste_de_matrices)`: met bout a bout en ligne des vecteurs/matrices de même nb de colonnes 

Pour l'exemple on peut juste convertir l'exemple à base de liste en `array`
```python
par_matière = np.array(notes_par_matière)
coeffs = np.array(coeffs)
```
#### 3.1
Comment peut-on avoir la matrice avec les notes de chaque étudiant par ligne ? 

In [11]:
import numpy as np

par_matière = np.array(notes_par_matière)
notes_par_etudiant = par_matière.T
print(notes_par_etudiant)

[[15  8 19]
 [ 2  5 15]
 [ 5 20 13]]


#### 3.2

La fonction suivante va servir à créer une matrice en dupliquant coeffs avec autant de lignes qu'il y a d'étudiants
```python
def coeffs_mat(coeffs,nb_etud):
    return np.array(list(coeffs)*nb_etud).reshape(...,...)
```
Quels sont les paramètres que l'on doit donner à reshape pour que cela remplisse l'objectif ? 

Sur l'exemple: 
```python
array([[5, 2, 2],
       [5, 2, 2],
       [5, 2, 2]])
```

In [12]:
def coeffs_mat(coeffs, nb_etud):
    return np.array(list(coeffs) * nb_etud).reshape(nb_etud, len(coeffs))

coeffs = np.array([5, 2, 2])
nb_etud = 3
print(coeffs_mat(coeffs, nb_etud))

[[5 2 2]
 [5 2 2]
 [5 2 2]]


#### 3.3 

Ecrire une fonction qui renvoie le vecteur des moyennes par étudiant à partir de la matrice de la question 3.1

In [13]:
print(np.mean(notes_par_etudiant, axis=1))

[14.          7.33333333 12.66666667]


#### 3.4  (attention : question peu facile)

Ecrire une fonction qui renvoie le vecteur des moyennes pondérées par les coefficients, en utilisant le résultat de la fonction 3.3  
Sur l'exemple cela donnerait:
```python
array([14.33333333,  5.55555556, 10.11111111])
```

In [14]:
print(np.sum(notes_par_etudiant*coeffs, axis=1) / np.sum(coeffs))

[14.33333333  5.55555556 10.11111111]


#### 3.5

On ne demande pas d'ajouter les moyennes à la matrice, on pourrait le faire
par exemple avec 
```python
def add_moyenne(m):
    mpe = moy_par_etud(m)
    return np.concatenate((m,mpe.reshape(1,3))).T
```

qui renverrait la matrice des notes par étudiants et leur moyenne, sur l'exemple
```python
array([[15.        ,  8.        , 19.        , 14.33333333],
       [ 2.        ,  5.        , 15.        ,  5.55555556],
       [ 5.        , 20.        , 13.        , 10.11111111]])
```
       
**A partir de cette matrice:**  
(a) Comment peut-on exprimer la condition qu'un étudiant doit avoir au moins 5 en poterie ? 
```python
condition_a = matrice_notes[:, 0] >= 5
```

(b) Comment peut-on exprimer la condition qu'un étudiant doit avoir au moins 10 de moyenne ? 
```python
condition_b = matrice_notes[:, -1] >= 10
```

(c) Comment peut-on exprimer la condition qu'un étudiant doit avoir au moins 6 à toutes les matières ? 
```python
condition_c = np.all(matrice_notes[:, :-1] >= 6, axis=1)
```

Ecrire une fonction qui prend la matrice de notes+moyenne, et qui retourner les lignes de la matrice de note correspondant aux étudiants qui "passent" selon les critères (b) et (c) (comme dans la partie 1)

Ici on doit donc avoir au final

```python
array([[15.        ,  8.        , 19.        , 14.33333333]])
```

[NB, pas demandé: on pourrait aussi utiliser np.argwhere pour avoir les indices des étudiants concernés à la place]

In [40]:
import numpy as np

def etudiants_passent(matrice_notes):
    condition_b = matrice_notes[:, -1] >= 10
    condition_c = np.all(matrice_notes[:, :-1] >= 6, axis=1)
    etudiants_acceptes = matrice_notes[np.logical_and(condition_b, condition_c)]
    return etudiants_acceptes

matrice_notes = np.array([[15.0, 8.0, 19.0, 14.33333333],
                         [2.0, 5.0, 15.0, 5.55555556],
                         [5.0, 20.0, 13.0, 10.11111111]])

print(etudiants_passent(matrice_notes))

[[15.          8.         19.         14.33333333]]
